apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web-lab
  labels:
    app: devops-web-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-web-lab
  template:
    metadata:
      labels:
        app: devops-web-lab
    spec:
      containers:
        - name: web
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
